#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','/','A','p','p','l','i','c','a',
        't','i','o','n','s','/','X','c','o','d','e','.','a','p','p','/','C','o',
        'n','t','e','n','t','s','/','D','e','v','e','l','o','p','e','r','/','u',
        's','r','/','b','i','n','/','g','c','c',' ','-','a','r','c','h',' ','x',
        '8','6','_','6','4',' ','-','I','.',' ','-','I','.','.',' ','-','I','.',
        '.','/','i','n','c','l','u','d','e',' ',' ','-','i','s','y','s','r','o',
        'o','t',' ','/','A','p','p','l','i','c','a','t','i','o','n','s','/','X',
        'c','o','d','e','.','a','p','p','/','C','o','n','t','e','n','t','s','/',
        'D','e','v','e','l','o','p','e','r','/','P','l','a','t','f','o','r','m',
        's','/','M','a','c','O','S','X','.','p','l','a','t','f','o','r','m','/',
        'D','e','v','e','l','o','p','e','r','/','S','D','K','s','/','M','a','c',
        'O','S','X','1','0','.','1','5','.','6','.','s','d','k',' ',' ','-','D',
        'O','P','E','N','S','S','L','_','T','H','R','E','A','D','S',' ','-','D',
        '_','R','E','E','N','T','R','A','N','T',' ','-','D','D','S','O','_','D',
        'L','F','C','N',' ','-','D','H','A','V','E','_','D','L','F','C','N','_',
        'H',' ','-','f','e','m','b','e','d','-','b','i','t','c','o','d','e',' ',
        '-','m','m','a','c','o','s','x','-','v','e','r','s','i','o','n','-','m',
        'i','n','=','1','0','.','1','1',' ','-','a','r','c','h',' ','x','8','6',
        '_','6','4',' ','-','O','3',' ','-','D','L','_','E','N','D','I','A','N',
        ' ','-','W','a','l','l','\0'
    };
    #define PLATFORM "platform: darwin64-x86_64-cc"
    #define DATE "built on: Sat Feb 27 23:35:59 2021"
#endif
